name 'nexus_sync'
maintainer 'Matt Ray'
maintainer_email 'matt@chef.io'
license 'Apache-2.0'
description 'Syncs a directory against Nexus'
version '0.2.0'
chef_version '>= 15.0'

source_url 'https://github.com/mattray/nexus_sync-cookbook'
issues_url 'https://github.com/mattray/nexus_sync-cookbook/issues'
